export const recruiters = [
  {
    name: "Aerfin Technologies PVT (LTD)",
    location: "San Francisco, Canada",
    industry: "Technology & Development",
    size: "11 - 50 Employees",
    since: "Member Since Feb 2024",
    image: "/img/AerFin1.png",
    description: `TalentConnect Group is a leading recruitment firm specializing in technology and startup talent acquisition. With over 12 years of experience in the industry, TalentConnect has built a reputation for delivering top-tier executive and technical professionals to some of the most innovative companies in Silicon Valley. From software engineers to product managers, the firm focuses on matching the best talent with growth-focused startups and mid-sized companies.`,
    contact: {
      phone: "011-2335-676",
      email: "info@aerfintechnologies.com",
    },
    phone: "011-2335-876",
    email: "info@aerfintechnologies.com",
    employees: "11 - 50 Employees",
    socialLinks: [
      { type: "facebook", url: "https://facebook.com/aerfin" },
      { type: "instagram", url: "https://instagram.com/aerfin" },
    ],
    memberSince: "Feb 2024",
  },
  {
    name: "Aerfin Technologies PVT (LTD)",
    location: "San Francisco, Canada",
    industry: "Technology & Development",
    size: "11 - 50 Employees",
    since: "Member Since Feb 2024",
    image: "/img/AerFin1.png",
    description: `TalentConnect Group is a leading recruitment firm specializing in technology and startup talent acquisition. With over 12 years of experience in the industry, TalentConnect has built a reputation for delivering top-tier executive and technical professionals to some of the most innovative companies in Silicon Valley. From software engineers to product managers, the firm focuses on matching the best talent with growth-focused startups and mid-sized companies.`,
    contact: {
      phone: "011-2335-676",
      email: "info@aerfintechnologies.com",
    },
    phone: "011-2335-876",
    email: "info@aerfintechnologies.com",
    employees: "11 - 50 Employees",
    socialLinks: [
      { type: "facebook", url: "https://facebook.com/aerfin" },
      { type: "instagram", url: "https://instagram.com/aerfin" },
    ],
    memberSince: "Feb 2024",
  },
  {
    name: "Aerfin Technologies PVT (LTD)",
    location: "San Francisco, Canada",
    industry: "Technology & Development",
    size: "11 - 50 Employees",
    since: "Member Since Feb 2024",
    image: "/img/AerFin1.png",
    description: `TalentConnect Group is a leading recruitment firm specializing in technology and startup talent acquisition. With over 12 years of experience in the industry, TalentConnect has built a reputation for delivering top-tier executive and technical professionals to some of the most innovative companies in Silicon Valley. From software engineers to product managers, the firm focuses on matching the best talent with growth-focused startups and mid-sized companies.`,
    contact: {
      phone: "011-2335-676",
      email: "info@aerfintechnologies.com",
    },
    phone: "011-2335-876",
    email: "info@aerfintechnologies.com",
    employees: "11 - 50 Employees",
    socialLinks: [
      { type: "facebook", url: "https://facebook.com/aerfin" },
      { type: "instagram", url: "https://instagram.com/aerfin" },
    ],
    memberSince: "Feb 2024",
  },

  {
    name: "Aerfin Technologies PVT (LTD)",
    location: "San Francisco, Canada",
    industry: "Technology & Development",
    size: "11 - 50 Employees",
    since: "Member Since Feb 2024",
    image: "/img/AerFin1.png",
    description: `TalentConnect Group is a leading recruitment firm specializing in technology and startup talent acquisition. With over 12 years of experience in the industry, TalentConnect has built a reputation for delivering top-tier executive and technical professionals to some of the most innovative companies in Silicon Valley. From software engineers to product managers, the firm focuses on matching the best talent with growth-focused startups and mid-sized companies.`,
    contact: {
      phone: "011-2335-676",
      email: "info@aerfintechnologies.com",
    },
    phone: "011-2335-876",
    email: "info@aerfintechnologies.com",
    employees: "11 - 50 Employees",
    socialLinks: [
      { type: "facebook", url: "https://facebook.com/aerfin" },
      { type: "instagram", url: "https://instagram.com/aerfin" },
    ],
    memberSince: "Feb 2024",
  },

  {
    name: "Aerfin Technologies PVT (LTD)",
    location: "San Francisco, Canada",
    industry: "Technology & Development",
    size: "11 - 50 Employees",
    since: "Member Since Feb 2024",
    image: "/img/AerFin1.png",
    description: `TalentConnect Group is a leading recruitment firm specializing in technology and startup talent acquisition. With over 12 years of experience in the industry, TalentConnect has built a reputation for delivering top-tier executive and technical professionals to some of the most innovative companies in Silicon Valley. From software engineers to product managers, the firm focuses on matching the best talent with growth-focused startups and mid-sized companies.`,
    contact: {
      phone: "011-2335-676",
      email: "info@aerfintechnologies.com",
    },
    phone: "011-2335-876",
    email: "info@aerfintechnologies.com",
    employees: "11 - 50 Employees",
    socialLinks: [
      { type: "facebook", url: "https://facebook.com/aerfin" },
      { type: "instagram", url: "https://instagram.com/aerfin" },
    ],
    memberSince: "Feb 2024",
  },
];
